-- AlterTable: adicionar campos completos do aluno em enrollments
ALTER TABLE `enrollments` ADD COLUMN `data_nascimento` DATETIME(3) NULL,
    ADD COLUMN `nome_responsavel` VARCHAR(255) NULL,
    ADD COLUMN `cpf` VARCHAR(14) NULL,
    ADD COLUMN `cpf_responsavel` VARCHAR(14) NULL,
    ADD COLUMN `curso` VARCHAR(50) NULL,
    ADD COLUMN `frequencia_semanal` INTEGER NULL,
    ADD COLUMN `tempo_aula_minutos` INTEGER NULL,
    ADD COLUMN `cep` VARCHAR(9) NULL,
    ADD COLUMN `rua` VARCHAR(255) NULL,
    ADD COLUMN `cidade` VARCHAR(100) NULL,
    ADD COLUMN `estado` VARCHAR(2) NULL,
    ADD COLUMN `numero` VARCHAR(20) NULL,
    ADD COLUMN `complemento` VARCHAR(255) NULL,
    ADD COLUMN `mora_no_exterior` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `endereco_exterior` TEXT NULL,
    ADD COLUMN `valor_mensalidade` DECIMAL(10, 2) NULL,
    ADD COLUMN `metodo_pagamento` VARCHAR(50) NULL,
    ADD COLUMN `dia_pagamento` INTEGER NULL,
    ADD COLUMN `melhores_horarios` VARCHAR(255) NULL,
    ADD COLUMN `melhores_dias_semana` VARCHAR(255) NULL,
    ADD COLUMN `nome_vendedor` VARCHAR(255) NULL,
    ADD COLUMN `nome_empresa_ou_indicador` VARCHAR(255) NULL,
    ADD COLUMN `observacoes` TEXT NULL;
